[ui.window.box]
width = 664
min_width = 664
max_width = 664
height = 596
min_height = 596
max_height = 596

# List constraints are critical - without these, the window shrinks when empty
[ui.window.box.scroll.list]
height = 552
min_height = 552
max_height = 552

[ui.window.box.scroll.list.item.icon]
pixel_size = 40
